<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="AccountingService" targetNamespace="urn:com.redhat.brq.integration.switchyard:1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:com.redhat.brq.integration.switchyard:1.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:portType name="AccountingServicePortType">
  </wsdl:portType>
  <wsdl:binding name="AccountingServiceSoapBinding" type="tns:AccountingServicePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="AccountingService">
    <wsdl:port name="AccountingServicePort" binding="tns:AccountingServiceSoapBinding">
      <soap:address location="http://localhost:8080/switchyard-integration-course/AccountingService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
