<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:tns="urn:com.redhat.brq.integration.exercise.inventory:1.0"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="InventoryService"
                  targetNamespace="urn:com.redhat.brq.integration.exercise.inventory:1.0">
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                    targetNamespace="urn:com.redhat.brq.integration.exercise.inventory:1.0">
            <xsd:element name="reserve" type="xsd:string">
            </xsd:element>
            <xsd:element name="response" type="xsd:string">
            </xsd:element>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="reserve">
        <wsdl:part name="parameters" element="tns:reserve"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="response">
        <wsdl:part name="parameters" element="tns:response"></wsdl:part>
    </wsdl:message>

    <wsdl:portType name="InventoryServicePortType">
        <wsdl:operation name="reserve">
            <wsdl:input message="tns:reserve"></wsdl:input>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:portType name="InventoryResponseServicePortType">
        <wsdl:operation name="response">
            <wsdl:input message="tns:response"></wsdl:input>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
